title: Mikhail Bakalov
email: mike@mbakalov.com
description: > #
baseurl: ""
url: "https://mbakalov.com"
github_username: mbakalov
linkedin_username: mbakalov

disqus:
    shortname: mbakalov

theme: minima
plugins:
  - jekyll-feed
