title: Mikhail Bakalov
email: mike@mbakalov.com
description: > #
baseurl: ""
url: "https://mbakalov.com"
github_username: mbakalov
linkedin_username: mbakalov

theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
